package teletext

import (
	"fmt"
	"testing"
)

func TestDecodeHash(t *testing.T) {
	var tests = map[string]string{
		"andyuglifruit-singing":       "#8:QIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECAp__tyOj___9CitejI-P_____________________vQor__yn9-R9f_______Pn7__________________________pRF_Kf-pHf_____________________________________9Smop__sCP______________________________________6oCn__9I6v_____________169GjRo0aNf_____________-0Kf___6R1___________-X4bP3_-___OBFXv___________0p_____0jr__________5f-tzf-77f__pyKBX__________yn______pFX________bl2rdr_btvuv-wQEUG__________Kf_______WBHf__v0aAugQ72v9r__6v_VARQav________8p_________9CKtugQIC_1Ag3f__bz___2hFBq_________yn__________-8ECBAgLokCBB________aoCP__________Kf____________6oECBAgQF9X_______9qgI__________8p______________0QIEBdB4_________0KAj_Xr169ejRoyn______________8v8-fP___________QICfDh8-fPn7__Kf______________y_______________9AgJqv________8p_______________Lol6_nz-fHf____p0BTQTRb_______yn9-nRo0aNGjRo0avf0Lq_________9ugQFEX1gT1______Kfw0HZsQZt_JBm38in_qXRb______pyn5AgQf__Qnr__1f8p_DYd2RBv3ZUGbfyKf___oXVf__9-U9f_iDB____pNf_KdCn8MgQIMOzYuXLkCAp__v06Evy582JRf__________-nDh_Kf_vzhw4cOHDhw4eP39uX4fv______-hRX____________8p________________ty_j-n3__69Wv__Sir___________yn_______________-X0PyPgu3I-PvQvvalNf__________QIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECA",
		"random":                      "#d:A0GLVkgQB4cWLGg2EDJAxaskE3fuQMmSCfj6A2DR00ar2LAvqRs9epGz16kbPWUOk0CBAg0NNDT4s-aHjz5oeJECBAgQIC-pAk16kCTXqQJ9ZQ6TQIECDU31tf_D_qatf-ruxQIECBAgLokaNGiRo0aJGjRlF69evXr1q5auWLFi1cuWLVi5evXr168HQ37NOPKgy7MuPpp37uaDZlw5tmXpzQcN_PplyIECBAgQIEEzLhzbMvTmgw4t_Xog3ZfHRBt37umhPzQZdmXH00793NAgQZt_JBw37NOPKgw7siDHy07cqDHv27dPPnp37svLmgw8sqBBiy6d2dBzy7uiDpvQMmKDbp2bNO_cg0b-vPLo37MnNcgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgDVt_TLy5oNO5Bh2bEHDDy6c0G_Mgi7s-zDuyIMO7IgQIECANXw7MvNBv69OenJlQTN-7Jv3IO-nZsQZdmXH0QYUCBAgQIA3DLy579yDpvQb-2Xlzy5UGXDj0IOG_Zpx5UGbfyx5UG_cgDMWqCdv7ZduLLyXIECBAgQIECBAgQIECBAgQIECBAgQIECAMgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIA1TRlQbsvdBj37dunnz0792XlzQd9OzYg5ZeGzDjyoECBAgDcN-zTjyoMPXpo38tPTTl5oNO5A0YoMPLLh5rkCBAgQIECAMgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIA1TRlQRdmXH038sOxBSy5t_Lagp78enL08oNmXDm2ZenNAgDZfHDZh07kG3fyyoMOLf16IOmjKg5b9mVBh3ZEHTRlQIECAN239NO7Og5-efTLtQYsundnQdeeXIsQYdunIgx792PLy3cw2_MgwoNm_ug6deW7f16IM3LftQdt_TLy5rkCBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECAodByN-3Kg3Ze_NBk058vPoHYtGIOvv5bMiDJpz5efQOxaMiZ0JI390EPLlzYfCDn309MejLzQdN6CJpz6emHYgqVkDZy3QIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECA",
		"polyducks-here-come-dat-boi": "#8:QIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECAv_____9AgQIEEiLSioIc-bFQRINRBCnyUCBAg_________y____________________36_f______________________L________________69GS8fOhff___________________8v_______________JPF___w_9C____________________y_______________8kq__Oe___L____________________L________________pLX_____8v___________________8v____________9enJfGv___-6-hfX_________________y__________3JbF6NGh1f____9Rpy__________________L____________8__3pLV_____9oX3f________________8v_____________-_JYG3___37_7Qvv________________y_____________35LB-Tol_1yhV_2hfX_______________L_____________JaH6Ev0QIEHgkq_tC_______________8v___________7Ul_YF_3_-g___5LV_L_______________y____________9SX9KX___6D___kvzcv_______________L_____________Jampd-jQIECPeS_l9H______________8v_____________6S-l0Hh0q04CX5KX________________y____________9ySFCXUckCQlg_Jy_7________________L________________6B6gYYCX8vs__________________8v________-_-a9am9tFD_1gJK05f__________________y_____________vmTsr6IFapIh8f___________________L______________9OfPn96cPH7____________________8udAIM-9B03oOGHPlQMWDJB03oOeXKg76MPRPzQdeC5AgQIC______________________________________________QIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECBAgQIECA",
	}
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			page, err := DecodeHash(test)
			if err != nil {
				t.Fatal(err)
			}
			testPage(t, page, fmt.Sprintf("testdata/hash-%s", name))
		})
	}
}
